// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAehMITCgLWCGvguRpx8I35jG-nFqX8Auc',
    appId: '1:155642764344:web:6456c996651af1f106dacd',
    messagingSenderId: '155642764344',
    projectId: 'dailyskincare-38173',
    authDomain: 'dailyskincare-38173.firebaseapp.com',
    storageBucket: 'dailyskincare-38173.firebasestorage.app',
    measurementId: 'G-B64QSRGDMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_hvIbEQHuHTYciI6YTsYMwVP9eZ3cCVI',
    appId: '1:155642764344:android:eee7fb6cb84929a306dacd',
    messagingSenderId: '155642764344',
    projectId: 'dailyskincare-38173',
    storageBucket: 'dailyskincare-38173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxZ_YClDrdVqdJ6J7TKBdsu4Vxr_t__E',
    appId: '1:155642764344:ios:1af6d4f44fdf671606dacd',
    messagingSenderId: '155642764344',
    projectId: 'dailyskincare-38173',
    storageBucket: 'dailyskincare-38173.firebasestorage.app',
    iosBundleId: 'com.app.dailyskincare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxxZ_YClDrdVqdJ6J7TKBdsu4Vxr_t__E',
    appId: '1:155642764344:ios:1af6d4f44fdf671606dacd',
    messagingSenderId: '155642764344',
    projectId: 'dailyskincare-38173',
    storageBucket: 'dailyskincare-38173.firebasestorage.app',
    iosBundleId: 'com.app.dailyskincare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAehMITCgLWCGvguRpx8I35jG-nFqX8Auc',
    appId: '1:155642764344:web:fa800cdedd72c68106dacd',
    messagingSenderId: '155642764344',
    projectId: 'dailyskincare-38173',
    authDomain: 'dailyskincare-38173.firebaseapp.com',
    storageBucket: 'dailyskincare-38173.firebasestorage.app',
    measurementId: 'G-TY5E44GF29',
  );
}
